# DOCKER
name: GitOps DOCKER CICD Pipeline
on:
  push:
    branches:
    - main
jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: 소스코드 전송
      uses: actions/checkout@v4
    
    - name: AWS 자격 증명 설정
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: 컨테이너 배포 및 S3 파일 싱크
      run: |
        aws ssm send-command \
          --instance-ids "i-098c52d8121bddab5" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[
            \"docker stop nginx-container || true\",
            \"docker rm nginx-container || true\",
            \"docker run -d --name nginx-container -p 80:80 nginx:1.31.3-alpine\"
          ]" \
          --region ${{secrets.AWS_REGION}} \
          --comment "Deploying SSM docker"